require: rubocop-rails

inherit_from:
  - https://gist.githubusercontent.com/dramancompany/68214fbedb21fa343919737ff3aebc9c/raw/rubocop.dnc.yml

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
